mysql:
  host: "localhost"
  port: 3306
  user: "minecraft"
  pass: "JToTl"
  db: "texasholdem_database"

minChipRate: 1 #int
maxChipRate: 10000000 #int
firstNumberOfChips: 30
canPlay: true

#最初の0~3はスペード、ダイヤ、ハート、クラブを表す
#その後は数字　14は1のこと

cardMaterial: "BIRCH_SAPLING"

faceDownCard:
  customModelData: 53

"0":
  "14":
    customModelData: 1
  "2":
    customModelData: 2
  "3":
    customModelData: 3
  "4":
    customModelData: 4
  "5":
    customModelData: 5
  "6":
    customModelData: 6
  "7":
    customModelData: 7
  "8":
    customModelData: 8
  "9":
    customModelData: 9
  "10":
    customModelData: 10
  "11":
    customModelData: 11
  "12":
    customModelData: 12
  "13":
    customModelData: 13

"1":
  "14":
    customModelData: 14
  "2":
    customModelData: 15
  "3":
    customModelData: 16
  "4":
    customModelData: 17
  "5":
    customModelData: 18
  "6":
    customModelData: 19
  "7":
    customModelData: 20
  "8":
    customModelData: 21
  "9":
    customModelData: 22
  "10":
    customModelData: 23
  "11":
    customModelData: 24
  "12":
    customModelData: 25
  "13":
    customModelData: 26

"2":
  "14":
    customModelData: 27
  "2":
    customModelData: 28
  "3":
    customModelData: 29
  "4":
    customModelData: 30
  "5":
    customModelData: 31
  "6":
    customModelData: 32
  "7":
    customModelData: 33
  "8":
    customModelData: 34
  "9":
    customModelData: 35
  "10":
    customModelData: 36
  "11":
    customModelData: 37
  "12":
    customModelData: 38
  "13":
    customModelData: 39

"3":
  "14":
    customModelData: 40
  "2":
    customModelData: 41
  "3":
    customModelData: 42
  "4":
    customModelData: 43
  "5":
    customModelData: 44
  "6":
    customModelData: 45
  "7":
    customModelData: 46
  "8":
    customModelData: 47
  "9":
    customModelData: 48
  "10":
    customModelData: 49
  "11":
    customModelData: 50
  "12":
    customModelData: 51
  "13":
    customModelData: 52
