mysql:
  host: "localhost"
  port: 3306
  user: "minecraft"
  pass: "JToTl"
  db: "texasholdem_database"

minChipRate: 1 #int
maxChipRate: 10000000 #int
firstNumberOfChips: 30
canPlay: true

#最初の0~3はスペード、ダイヤ、ハート、クラブを表す
#その後は数字　14は1のこと

cardMaterial: "BIRCH_SAPLING"

faceDownCard:
  customModelData: 53

"0":
  "14":
    customModelData: 1
  "2":
    customModelData: 2
  "3":
    customModelData: 3
  "4":
    customModelData: 4
  "5":
    customModelData: 5
  "6":
    customModelData: 6
  "7":
    customModelData: 7
  "8":
    customModelData: 8
  "9":
    customModelData: 9
  "10":
    customModelData: 10
  "11":
    customModelData: 11
  "12":
    customModelData: 12
  "13":
    customModelData: 13

"1":
  "14":
    customModelData: 14
  "2":
    customModelData: 15
  "3":
    customModelData: 16
  "4":
    customModelData: 17
  "5":
    customModelData: 18
  "6":
    customModelData: 19
  "7":
    customModelData: 20
  "8":
    customModelData: 21
  "9":
    customModelData: 22
  "10":
    customModelData: 23
  "11":
    customModelData: 24
  "12":
    customModelData: 25
  "13":
    customModelData: 26

"2":
  "14":
    customModelData: 27
  "2":
    customModelData: 28
  "3":
    customModelData: 29
  "4":
    customModelData: 30
  "5":
    customModelData: 31
  "6":
    customModelData: 32
  "7":
    customModelData: 33
  "8":
    customModelData: 34
  "9":
    customModelData: 35
  "10":
    customModelData: 36
  "11":
    customModelData: 37
  "12":
    customModelData: 38
  "13":
    customModelData: 39

"3":
  "14":
    customModelData: 40
  "2":
    customModelData: 41
  "3":
    customModelData: 42
  "4":
    customModelData: 43
  "5":
    customModelData: 44
  "6":
    customModelData: 45
  "7":
    customModelData: 46
  "8":
    customModelData: 47
  "9":
    customModelData: 48
  "10":
    customModelData: 49
  "11":
    customModelData: 50
  "12":
    customModelData: 51
  "13":
    customModelData: 52

texasholdeminv:
  "45":
    material: "WHITE_STAINED_GLASS_PANE"
    name: ""
    lore: ""
  "46":
    material: "BLUE_STAINED_GLASS_PANE"
    name: "§w§lフォールド"
    lore: ""
  "47":
    material: "PINK_STAINED_GLASS_PANE"
    name: "§w§lレイズ"
    lore: ""
  "48":
    material: "RED_STAINED_GLASS_PANE"
    name: "§w§lチェック"
    lore: ""
  "49":
    material: "YELLOW_STAINED_GLASS_PANE"
    name: "§w§lベット"
    lore: ""
  "50":
    material: "GREEN_STAINED_GLASS_PANE"
    name: "§w§lコール"
    lore: ""
  "51":
    material: "BROWN_STAINED_GLASS_PANE"
    name: "§w§lオールイン"
    lore: ""
  "52":
    material: "WHITE_STAINED_GLASS_PANE"
    name: ""
    lore: ""

raise:
  "45":
    material: "BARRIER"
    name: "§4§l戻る"
    lore:
  "46":
    material: "RED_WOOL"
    name: "§c§l賭けチップを一枚減らす"
    lore:
  "47":
    material: "WHITE_STAINED_GLASS_PANE"
    name: "empty"
    lore:
  "48":
    material: "WHITE_STAINED_GLASS_PANE"
    name: "empty"
    lore:
  "49":
    material: "GREEN_WOOL"
    name: "§a§l以下の枚数でチップを上乗せする"
    lore:
  "50":
    material: "WHITE_STAINED_GLASS_PANE"
    name: "empty"
    lore:
  "51":
    material: "WHITE_STAINED_GLASS_PANE"
    name: "empty"
    lore:
  "52":
    material: "BLUE_WOOL"
    name: "§9§l賭けチップを一枚増やす"
    lore:


