mysql:
  host: "localhost"
  port: 3306
  user: "minecraft"
  pass: "JToTl"
  db: "texasholdem_database"

minChipRate: 1000
maxChipRate: 10000000
firstNumberOfChips: 30

#最初の0~3はスペード、ダイヤ、ハート、クラブを表す
#その後は数字　14は1のこと

cardMaterial: "GOLD_NUGGET"

faceDownCard:
  customModelData: 777

"0":
  "14":
    customModelData: 1
  "2":
    customModelData: 2
  "3":
    customModelData: 3
  "4":
    customModelData: 4
  "5":
    customModelData: 5
  "6":
    customModelData: 6
  "7":
    customModelData: 7
  "8":
    customModelData: 8
  "9":
    customModelData: 9
  "10":
    customModelData: 10
  "11":
    customModelData: 11
  "12":
    customModelData: 12
  "13":
    customModelData: 13

"1":
  "14":
    customModelData: 101
  "2":
    customModelData: 102
  "3":
    customModelData: 103
  "4":
    customModelData: 104
  "5":
    customModelData: 105
  "6":
    customModelData: 106
  "7":
    customModelData: 107
  "8":
    customModelData: 108
  "9":
    customModelData: 109
  "10":
    customModelData: 110
  "11":
    customModelData: 111
  "12":
    customModelData: 112
  "13":
    customModelData: 113

"2":
  "14":
    customModelData: 201
  "2":
    customModelData: 202
  "3":
    customModelData: 203
  "4":
    customModelData: 204
  "5":
    customModelData: 205
  "6":
    customModelData: 206
  "7":
    customModelData: 207
  "8":
    customModelData: 208
  "9":
    customModelData: 209
  "10":
    customModelData: 210
  "11":
    customModelData: 211
  "12":
    customModelData: 212
  "13":
    customModelData: 213

"3":
  "14":
    customModelData: 301
  "2":
    customModelData: 302
  "3":
    customModelData: 303
  "4":
    customModelData: 304
  "5":
    customModelData: 305
  "6":
    customModelData: 306
  "7":
    customModelData: 307
  "8":
    customModelData: 308
  "9":
    customModelData: 309
  "10":
    customModelData: 310
  "11":
    customModelData: 311
  "12":
    customModelData: 312
  "13":
    customModelData: 313

texasholdeminv:
  "45":
    material: "WHITE_STAINED_GLASS_PANE"
    name: ""
    lore: ""
  "46":
    material: "BLUE_STAINED_GLASS_PANE"
    name: "§w§lフォールド"
    lore: ""
  "47":
    material: "PINK_STAINED_GLASS_PANE"
    name: "§w§lレイズ"
    lore: ""
  "48":
    material: "RED_STAINED_GLASS_PANE"
    name: "§w§lチェック"
    lore: ""
  "49":
    material: "YELLOW_STAINED_GLASS_PANE"
    name: "§w§lベット"
    lore: ""
  "50":
    material: "GREEN_STAINED_GLASS_PANE"
    name: "§w§lコール"
    lore: ""
  "51":
    material: "BROWN_STAINED_GLASS_PANE"
    name: "§w§lオールイン"
    lore: ""
  "52":
    material: "WHITE_STAINED_GLASS_PANE"
    name: ""
    lore: ""

raise:
  "45":
    material: "BARRIER"
    name: "§4§l戻る"
    lore:
  "46":
    material: "RED_WOOL"
    name: "§c§l賭けチップを一枚減らす"
    lore:
  "47":
    material: "WHITE_STAINED_GLASS_PANE"
    name:
    lore:
  "48":
    material: "WHITE_STAINED_GLASS_PANE"
    name:
    lore:
  "49":
    material: "GREEN_WOOL"
    name: "§a§l以下の枚数でチップを上乗せする"
    lore:
  "50":
    material: "WHITE_STAINED_GLASS_PANE"
    name:
    lore:
  "51":
    material: "WHITE_STAINED_GLASS_PANE"
    name:
    lore:
  "52":
    material: "BLUE_WOOL"
    name: "§9§l賭けチップを一枚増やす"
    lore:


