name: TexasHoldem_kotlin
version: @version@
main: ltotj.minecraft.texasholdem_kotlin.Main
api-version: 1.16
depend: [Vault]
commands:
  poker:
    usage: "/poker help で使い方を確認しましょう"

permissions:
  poker.switch:
    default: op
  poker.player:
    default: true
