name: TexasHoldem_kotlin
version: @version@
main: ltotj.minecraft.texasholdem_kotlin.Main
api-version: 1.17
depend:
  - Vault
commands:
  poker:
    usage: "/poker help で使い方を確認しましょう"
  aof:
    usage: "/aof help"

permissions:
  poker.admin:
    default: op
  poker.player:
    default: true
