name: TexasHoldem
version: @version@
main: ltotj.minecraft.texasholdem.Main
api-version: 1.17
depend: [Vault]
commands:
  poker:
    usage: "/poker help で使い方を確認しましょう"

permissions:
  poker.switch:
    default: op
  poker.player:
    default: true
